[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200

[profile.default.fmt]
line_length = 100
tab_width = 4
bracket_spacing = false

# Monad Testnet
[rpc_endpoints]
monad_testnet = "${MONAD_TESTNET_RPC_URL}"

[etherscan]
monad_testnet = { key = "${EXPLORER_API_KEY}" }
